name: vint
version: 0.6.1
description: >
  VINT is a framework for writing single-page applications in Dart.
author: Victor Savkin <vic.savkin@gmail.com>
homepage: http://vintdart.com
dependencies:
  unittest: any
  browser: any
  dartmocks: any